import type { RoleThemeTokenKey } from "@/lib/theme/types";

/** Maps semantic token keys to CSS custom property names on :root. */
export const TOKEN_TO_CSS_VAR: Record<RoleThemeTokenKey, string> = {
  primary: "--theme-primary",
  primaryHover: "--theme-primary-hover",
  primaryForeground: "--theme-primary-foreground",
  secondary: "--theme-secondary",
  secondaryForeground: "--theme-secondary-foreground",
  background: "--theme-background",
  surface: "--theme-surface",
  surfaceMuted: "--theme-surface-muted",
  border: "--theme-border",
  borderMuted: "--theme-border-muted",
  textPrimary: "--theme-text-primary",
  textSecondary: "--theme-text-secondary",
  textMuted: "--theme-text-muted",
  accent: "--theme-accent",
  accentForeground: "--theme-accent-foreground",
  badgeBg: "--theme-badge-bg",
  badgeText: "--theme-badge-text",
  badgeSuccessBg: "--theme-badge-success-bg",
  badgeSuccessText: "--theme-badge-success-text",
  badgeWarningBg: "--theme-badge-warning-bg",
  badgeWarningText: "--theme-badge-warning-text",
  buttonPrimary: "--theme-button-primary",
  buttonPrimaryHover: "--theme-button-primary-hover",
  buttonPrimaryText: "--theme-button-primary-text",
  buttonSecondary: "--theme-button-secondary",
  buttonSecondaryText: "--theme-button-secondary-text",
  statusSuccess: "--theme-status-success",
  statusWarning: "--theme-status-warning",
  statusError: "--theme-status-error",
  statusInfo: "--theme-status-info",
  focusRing: "--theme-focus-ring",
  bannerBg: "--theme-banner-bg",
  heading: "--theme-heading",
};
